[tool.poetry]
name = "f1data"
version = "0.1.0"
description = ""
authors = ["German <thewhitehaven04@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.1"
fastf1 = "3.4.0"
fastapi = "0.112"
pandera = "^0.20.4"
pydantic = "1.10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
